const demoProducts = [
  {
    title: 'Vintage Casino Token Set',
    description: 'Custom casino tokens for event games, party prizes, and tabletop decor.',
    price: 19.99,
    quantity: 120,
    category: 'Assets',
    subCategory: 'Guest Pickup Card',
    imageUrls: ['/Assets/demo-casino-tokens-1.jpg', '/Assets/demo-casino-tokens-2.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Personalized Event Sign Board',
    description: 'Acrylic sign board with customizable text and premium finish for any celebration.',
    price: 34.5,
    quantity: 50,
    category: 'Boards & Signage',
    subCategory: 'Playful Sign',
    imageUrls: ['/Assets/demo-sign-board-1.jpg', '/Assets/demo-sign-board-2.jpg'],
    hasVariants: true,
    variantTitle: 'Design Style',
    variantImages: ['/Assets/demo-sign-board-style-1.jpg', '/Assets/demo-sign-board-style-2.jpg'],
  },
  {
    title: 'Luxury Room Welcome Kit',
    description: 'Hotel room stationery kit with greeting note, information card, and a gift tag.',
    price: 29.99,
    quantity: 75,
    category: 'Room Stationery',
    subCategory: 'Welcome Note',
    imageUrls: ['/Assets/demo-welcome-kit-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Dual-Tip Party Markers',
    description: 'Vivid markers for signage, seating charts, and creative event designs.',
    price: 12.75,
    quantity: 200,
    category: 'Utility Stationery',
    subCategory: 'Markers',
    imageUrls: ['/Assets/demo-markers-1.jpg', '/Assets/demo-markers-2.jpg'],
    hasVariants: true,
    variantTitle: 'Color Pack',
    variantImages: ['/Assets/demo-marker-set-1.jpg'],
  },
  {
    title: 'Acrylic Favor Trophy',
    description: 'Mini acrylic trophies that double as keepsakes for guests and award winners.',
    price: 22.0,
    quantity: 90,
    category: 'Favour & Gifts',
    subCategory: 'Bells With Tags',
    imageUrls: ['/Assets/demo-favor-trophy-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Custom Wedding Invitation',
    description: 'Printed wedding invite with elegant script, foil accents, and custom details.',
    price: 55.0,
    quantity: 60,
    category: 'Invites & Planner',
    subCategory: 'E-Invite',
    imageUrls: ['/Assets/demo-wedding-invite-1.jpg', '/Assets/demo-wedding-invite-2.jpg'],
    hasVariants: true,
    variantTitle: 'Paper Finish',
    variantImages: ['/Assets/demo-invite-finish-1.jpg'],
  },
  {
    title: 'Photo Frame Guest Pick-Up Card',
    description: 'Personalized guest pick-up cards with a stylish photo frame design.',
    price: 25.0,
    quantity: 80,
    category: 'Assets',
    subCategory: 'Guest Pickup Card',
    imageUrls: ['/Assets/demo-guest-pickup-card-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Wedding Contact Board',
    description: 'Large contact board to showcase social media handles and wedding hashtags.',
    price: 42.5,
    quantity: 40,
    category: 'Boards & Signage',
    subCategory: 'Wedding Contact Board',
    imageUrls: ['/Assets/demo-contact-board-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Bride & Groom Door Dangler',
    description: 'Personalized door dangler to welcome guests at the event venue.',
    price: 18.5,
    quantity: 100,
    category: 'Room Stationery',
    subCategory: 'Door Dangler',
    imageUrls: ['/Assets/demo-door-dangler-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Printed Itinerary Booklet',
    description: 'Compact itinerary book for guests with event schedule and venue details.',
    price: 16.0,
    quantity: 150,
    category: 'Room Stationery',
    subCategory: 'Itinerary',
    imageUrls: ['/Assets/demo-itinerary-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Custom Ritual Kit Box',
    description: 'Complete ritual kit with custom label, perfect for pre-wedding ceremonies.',
    price: 30.0,
    quantity: 70,
    category: 'Utility Stationery',
    subCategory: 'Ritual Kit',
    imageUrls: ['/Assets/demo-ritual-kit-1.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Printed Menu Card Set',
    description: 'Set of menu cards with elegant typography for reception dining tables.',
    price: 28.0,
    quantity: 120,
    category: 'Utility Stationery',
    subCategory: 'Menu Card',
    imageUrls: ['/Assets/demo-menu-card-1.jpg'],
    hasVariants: true,
    variantTitle: 'Card Shape',
    variantImages: ['/Assets/demo-menu-card-shape-1.jpg'],
  },
  {
    title: 'Instagram Filter Frame',
    description: 'Fun Instagram / Snapchat filter props for photo booths and guest interaction.',
    price: 12.0,
    quantity: 180,
    category: 'Fun & Entertainment',
    subCategory: 'Instagram / Snapchat Filter',
    imageUrls: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz7xw_FW2d4C805nnn7LN1gVT9SStCLwlSjQ&s'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Tambola Ticket Pack',
    description: 'Colorful tambola tickets for games, party spots, and entertainment stalls.',
    price: 10.5,
    quantity: 140,
    category: 'Fun & Entertainment',
    subCategory: 'Tambola Tickets',
    imageUrls: ['https://m.media-amazon.com/images/I/81n4i3SKY-L._AC_UF1000,1000_QL80_.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Tea Light Candle Cones',
    description: 'Decorative petal cone candle holders for event tables and aisle decor.',
    price: 15.0,
    quantity: 110,
    category: 'Thermatic Elements',
    subCategory: 'Petal Cones',
    imageUrls: ['https://i.etsystatic.com/44109879/r/il/88355f/6606238325/il_570xN.6606238325_qhu7.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Custom Printed Paper Cups',
    description: 'Disposable paper cups with custom artwork for drinks and welcome stations.',
    price: 14.0,
    quantity: 130,
    category: 'Thermatic Elements',
    subCategory: 'Paper Cups',
    imageUrls: ['https://i.etsystatic.com/21247972/r/il/9d7370/7822998663/il_570xN.7822998663_fspd.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Gold Foil Chocolate Wrapper',
    description: 'Premium wrapper for chocolate favors with elegant gold foil finish.',
    price: 9.5,
    quantity: 200,
    category: 'Favour & Gifts',
    subCategory: 'Chocolate Wrapper',
    imageUrls: ['https://i.pinimg.com/736x/49/80/29/498029f533ea97e2903b111374acd80f.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Jute Gift Bag Set',
    description: 'Eco-friendly jute bags for favors, gifts, and product packaging.',
    price: 20.0,
    quantity: 95,
    category: 'Favour & Gifts',
    subCategory: 'Jute Bags',
    imageUrls: ['https://www.handmakers.in/cdn/shop/files/lamansh-jute-gift-bags-lamansh-printed-jute-gift-bags-10-x-9-5-x-4-traditional-jute-return-gifts-bags-for-festive-wedding-ceremony-30491843821629_1800x1800_21d47f04-20db-4623-89cb-7132efc7f681.jpg?v=1690191568'],
    hasVariants: true,
    variantTitle: 'Bag Size',
    variantImages: ['https://m.media-amazon.com/images/I/81N-NAw-xxL._AC_UF894,1000_QL80_.jpg'],
  },
  {
    title: 'Stationery Wedding Planner',
    description: 'A detailed wedding planner notebook to keep all event notes and checklists organized.',
    price: 26.0,
    quantity: 80,
    category: 'Invites & Planner',
    subCategory: 'Wardrobe Planner',
    imageUrls: ['https://www.countybrides.com/wp-content/uploads/2024/03/LUXURY-WEDDING-STATIONERY-1200x800.jpg'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  },
  {
    title: 'Custom Logo Sticker Set',
    description: 'Personalized stickers and logo designs for invites, gift tags, and event branding.',
    price: 17.5,
    quantity: 160,
    category: 'Invites & Planner',
    subCategory: 'Logo',
    imageUrls: ['https://stickerme.in/wp-content/uploads/2023/04/Bride-and-Groom-Green-1_.webp'],
    hasVariants: false,
    variantTitle: null,
    variantImages: [],
  }
];

export default demoProducts;
